config/routes.rb
Rails.application.routes.draw do
  resources :article_histories
  resources :texts
  resources :assignments
  resources :types
  resources :articles
  resources :conferences
  resources :journals
  resources :states
  resources :researches
  resources :researchers
  resources :faculties
  resources :universities
  root 'page#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :research
	has_many :texts
  has_many :article_histories
end

app/models/article_history.rb
class ArticleHistory < ActiveRecord::Base
  belongs_to :article
  belongs_to :state
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :research
	belongs_to :researcher
	belongs_to :type
end

app/models/conference.rb
class Conference < ActiveRecord::Base
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :university
  has_many :researchers
end

app/models/journal.rb
class Journal < ActiveRecord::Base
end

app/models/research.rb
class Research < ActiveRecord::Base
	has_many :assignments
	has_many :articles
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base
	belongs_to :faculty
	has_many :assignments
	has_many :texts

	def name
		return first_name + " " + last_name
	end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :article_histories
end

app/models/text.rb
class Text < ActiveRecord::Base
	belongs_to :researcher
	belongs_to :article
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :assignments
end

app/models/university.rb
class University < ActiveRecord::Base
  has_many :faculties
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new

    @universities = University.all
  end

  # GET /faculties/1/edit
  def edit
    @universities = University.all
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :description, :university_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <label>University:</label>
    <%= f.collection_select(:university_id, @universities, :id, :name) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Editing Faculty</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Show', @faculty %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', faculties_path %>
    </button>
  </div>
</div>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h3>Listing Faculties</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>University</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @faculties.each do |faculty| %>
        <tr>
          <td><%= faculty.name %></td>
          <td><%= faculty.description %></td>
          <td><%= faculty.university.name %></td>
          <td><%= link_to 'Show', faculty %></td>
          <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
          <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <button type="button" class="btn btn-default">
    <%= link_to 'New Faculty', new_faculty_path %>
  </button>
</div>

app/views/faculties/new.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">New Faculty</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', faculties_path %>
    </button>
  </div>
</div>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form-group">
    <label class="control-label">Name:</label>
    <div class="">
      <%= @faculty.name %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Description:</label>
    <div class="">
      <%= @faculty.description %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">University:</label>
    <div class="">
      <%= @faculty.university.name %>
    </div>
  </div>
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_faculty_path(@faculty) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', faculties_path %></button>
</div>