config/routes.rb
Rails.application.routes.draw do
  resources :article_histories
  resources :texts
  resources :assignments
  resources :types
  resources :articles
  resources :conferences
  resources :journals
  resources :states
  resources :researches
  resources :researchers
  resources :faculties
  resources :universities
  root 'page#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :research
	has_many :texts
  has_many :article_histories
end

app/models/article_history.rb
class ArticleHistory < ActiveRecord::Base
  belongs_to :article
  belongs_to :state
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :research
	belongs_to :researcher
	belongs_to :type
end

app/models/conference.rb
class Conference < ActiveRecord::Base
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :university
  has_many :researchers
end

app/models/journal.rb
class Journal < ActiveRecord::Base
end

app/models/research.rb
class Research < ActiveRecord::Base
	has_many :assignments
	has_many :articles
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base
	belongs_to :faculty
	has_many :assignments
	has_many :texts

	def name
		return first_name + " " + last_name
	end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :article_histories
end

app/models/text.rb
class Text < ActiveRecord::Base
	belongs_to :researcher
	belongs_to :article
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :assignments
end

app/models/university.rb
class University < ActiveRecord::Base
  has_many :faculties
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :place, :sponsor, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :sponsor %><br>
    <%= f.text_field :sponsor %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Editing Conference</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Show', @conference %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', conferences_path %>
    </button>
  </div>
</div>

app/views/conferences/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h3>Listing Conferences</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Place</th>
        <th>Sponsor</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @conferences.each do |conference| %>
        <tr>
          <td><%= conference.name %></td>
          <td><%= conference.place %></td>
          <td><%= conference.sponsor %></td>
          <td><%= conference.date %></td>
          <td><%= link_to 'Show', conference %></td>
          <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
          <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <button type="button" class="btn btn-default">
    <%= link_to 'New Conference', new_conference_path %>
  </button>
</div>

app/views/conferences/new.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">New Conference</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', conferences_path %>
    </button>
  </div>
</div>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form-group">
    <label class="control-label">Name:</label>
    <div class="">
      <%= @conference.name %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Place:</label>
    <div class="">
      <%= @conference.place %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Sponsor:</label>
    <div class="">
      <%= @conference.sponsor %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Date:</label>
    <div class="">
      <%= @conference.date %>
    </div>
  </div>
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_conference_path(@conference) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', conferences_path %></button>
</div>