config/routes.rb
Rails.application.routes.draw do
  resources :article_histories
  resources :texts
  resources :assignments
  resources :types
  resources :articles
  resources :conferences
  resources :journals
  resources :states
  resources :researches
  resources :researchers
  resources :faculties
  resources :universities
  root 'page#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :research
	has_many :texts
  has_many :article_histories
end

app/models/article_history.rb
class ArticleHistory < ActiveRecord::Base
  belongs_to :article
  belongs_to :state
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :research
	belongs_to :researcher
	belongs_to :type
end

app/models/conference.rb
class Conference < ActiveRecord::Base
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :university
  has_many :researchers
end

app/models/journal.rb
class Journal < ActiveRecord::Base
end

app/models/research.rb
class Research < ActiveRecord::Base
	has_many :assignments
	has_many :articles
end

app/models/researcher.rb
class Researcher < ActiveRecord::Base
	belongs_to :faculty
	has_many :assignments
	has_many :texts

	def name
		return first_name + " " + last_name
	end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :article_histories
end

app/models/text.rb
class Text < ActiveRecord::Base
	belongs_to :researcher
	belongs_to :article
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :assignments
end

app/models/university.rb
class University < ActiveRecord::Base
  has_many :faculties
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:name, :company, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_area :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Editing Journal</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Show', @journal %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', journals_path %>
    </button>
  </div>
</div>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h3>Listing Journals</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Company</th>
        <th>Link</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @journals.each do |journal| %>
        <tr>
          <td><%= journal.name %></td>
          <td><%= journal.company %></td>
          <td><%= journal.link %></td>
          <td><%= link_to 'Show', journal %></td>
          <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
          <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <button type="button" class="btn btn-default">
    <%= link_to 'New Journal', new_journal_path %>
  </button>
</div>

app/views/journals/new.html.erb
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">New Journal</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to 'Back', journals_path %>
    </button>
  </div>
</div>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="form-group">
    <label class="control-label">Name:</label>
    <div class="">
      <%= @journal.name %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Company:</label>
    <div class="">
      <%= @journal.company %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label">Link:</label>
    <div class="">
      <%= @journal.link %>
    </div>
  </div>
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_journal_path(@journal) %></button>
  <button type="button" class="btn btn-default"><%= link_to 'Back', journals_path %></button>
</div>